version: '2'
services:
  broker:
    image: toke/mosquitto
    ports:
     - "1883:1883"
     - "9001:9001"
  web:
    image: nginx
    ports:
     - "8080:80"
    volumes:
     - ./ui:/usr/share/nginx/html:ro
    links:
     - broker
  rps:
    build: rps
    volumes:
     - ./rps:/rps:ro
    devices:
     - /dev/video0
    command: python3 /rps/rps.py
    links:
     - broker
  gamemaster:
    build: ./framework/gamemaster
    volumes:
     - ./framework:/framework:rw
    command: python3 /framework/run_gamemaster.py
    links:
     - broker